#!/bin/bash

# generate colors
wal --backend haishoku --cols16 -i $1 -n
# send save events to reload configs
touch /home/duck/.config/rio/config.toml
touch /home/duck/.config/vesktop/themes/system24.theme.css
# reload mango config
mmsg -d reload_config
# change background
awww img $1 -t grow --transition-step 90 --transition-duration 1.7 --transition-pos top-right
# reload browser homepage
starttree &
# reload swaync
killall swaync
swaync &
# reload gtk theme
oomox-cli -o pywal /home/duck/.cache/wal/colors-oomox
