#!/bin/bash

wal --backend haishoku --cols16 -i $1 -n
swww img $1 -t grow --transition-step 90 --transition-duration 1.7 --transition-pos top-right

killall swaync
swaync &
pywal-discord -t duck -p /home/duck/.config/vesktop/themes
oomox-cli -o pywal /home/duck/.cache/wal/colors-oomox
