// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1773575958);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1773575172);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 163);
user_pref("browser.newtabpage.activity-stream.impressionId", "{38d1202a-62b2-4437-ba08-771efd898cc2}");
user_pref("browser.newtabpage.activity-stream.system.showWeatherOptIn", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1773575173);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1773575175766");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1773596775766");
user_pref("browser.search.region", "PT");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20260216111642");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20260216111642");
user_pref("browser.startup.homepage_override.mstone", "148.0");
user_pref("browser.startup.lastColdStartupCheck", 1773575958);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"glide-toolbar-mode-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"glide-toolbar-keyseq-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 6);
user_pref("captchadetection.lastSubmission", 1773575);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe");
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("distribution.iniFile.exists.appversion", "0.1.59a");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "PT");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "84d1ab8d155d4a8d948ffdfed950d98a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.dnr.lastStoreUpdateTag.c1379070-60be-4714-94d0-77545d7e805f", "{d3057ebc-3622-4c33-9777-a8551e5b4c80}");
user_pref("extensions.lastAppBuildId", "20260216111642");
user_pref("extensions.lastAppVersion", "0.1.59a");
user_pref("extensions.lastPlatformVersion", "148.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_interventions", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.glide-internal@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"cfedbdef-3200-48c4-b461-51b77bff6172\",\"formautofill@mozilla.org\":\"75c39a3d-f60f-412e-b6c8-d5460611660d\",\"ipp-activator@mozilla.com\":\"f68edaf1-390c-488d-b5d5-a9f6438aa0b6\",\"pictureinpicture@mozilla.org\":\"96a862c3-979c-4f27-a6e0-a55c612de67c\",\"addons-search-detection@mozilla.com\":\"4e42b1f8-e3b8-4d51-af5a-23305f60db2e\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"glide-internal@mozilla.org\":\"c1379070-60be-4714-94d0-77545d7e805f\",\"newtab@mozilla.org\":\"bc6bb314-3d85-4f64-ba87-cc2f3a1e2f94\",\"default-theme@mozilla.org\":\"cff0f359-f73f-4ca9-8c2a-36645440ef1d\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.dmabuf", 4);
user_pref("gfx.blacklist.dmabuf.failureid", "FEATURE_FAILURE_DL_BLOCKLIST_NO_ID");
user_pref("gfx.blacklist.gl.threadsafe", 4);
user_pref("gfx.blacklist.gl.threadsafe.failureid", "FEATURE_FAILURE_DL_BLOCKLIST_NO_ID");
user_pref("glide.notifications.scroll_instant_to_smooth", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "7481bdf5-db42-4f35-8d3f-7cfd8556da01");
user_pref("nimbus.rollouts.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("privacy.trackingprotection.allow_list.hasUserInteractedWithETPSettings", true);
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.extension", "glide-internal@mozilla.org");
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.storeID", "a9399615");
user_pref("toolkit.startup.last_success", 1773575957);
user_pref("toolkit.telemetry.cachedClientID", "eceef89f-4e67-4559-bbd8-a7cd2207901b");
user_pref("toolkit.telemetry.cachedProfileGroupID", "14902b4c-beb8-4f31-b40b-cbc5077fcc23");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
