rootcolor={color0.strip}ff
bordercolor={color4.strip}ff
focuscolor={color9.strip}ff
urgentcolor={color13.strip}ff
scratchpadcolor={color11.strip}ff
globalcolor={color1.strip}ff
overlaycolor={color3.strip}ff
