[colors]
background = '{color0}8e'
black = '{color0}'
blue = '{color4}'
cursor = '{color15}'
cyan = '{color6}'
foreground = '{color15}'
green = '{color2}'
magenta = '{color5}'
red = '{color1}'
tabs = '{color8}'
tabs-active = '{color9}'
white = '{color7}'
yellow = '{color3}'
dim-black = '{color0}8e'
dim-blue = '{color4}8e'
dim-cyan = '{color6}8e'
dim-foreground = '{color7}8e'
dim-green = '{color2}8e'
dim-magenta = '{color5}8e'
dim-red = '{color1}8e'
dim-white = '{color7}8e'
dim-yellow = '{color3}8e'
light-black = '{color8}'
light-blue = '{color12}'
light-cyan = '{color14}'
light-foreground = '{color15}'
light-green = '{color10}'
light-magenta = '{color13}'
light-red = '{color9}'
light-white = '{color15}'
light-yellow = '{color11}'
