#env

env=MOZ_ENABLE_WAYLAND,1
env=QT_QPA_PLATFORM,wayland
env=CLUTTER_BACKEND,wayland
env=ECORE_EVAS_ENGINE,wayland-egl
env=ELM_ENGINE,wayland_egl
env=XDG_SESSION_TYPE,wayland
env=XDG_CURRENT_DESKTOP,mango
env=QT_QPA_PLATFORMTHEME,qt6ct

numlockon=0

# window rules
windowrule=isfloating:1,width:20%,height:50%,offsety:-50,offsetx:-20,appid:wofi
windowrule=isfloating:1,width:20%,height:50%,offsety:-50,offsetx:-40,appid:keepassxc
windowrule=isfloating:1,width:1000,height:2000,offsety:-50,offsetx:-40,appid:satty
windowrule=isterm:0,noswallow:0,appid:org.pwmt.zathura
windowrule=isterm:1,noswallow:0,appid:kitty
windowrule=isfloating:1,width:350,height:500,title:launcher
windowrule=isglobal:1,isfloating:1,istagsilent:1,height:300%,width:500%,offsetx:100,offsety:-100,title:tomato

# layer rules
#layerrule=noblur:1,layer_name:swaync-control-center
#layerrule=noshadow:1,noblur:1,layer_name:swaync-notification-window
layerrule=layer_name:selection,noblur:1,animation_type_open:fade,animation_type_close:fade
layerrule=layer_name:msnap,noblur:1,noanim:1
layerrule=layer_name:hyprpicker,noanim:1, noblur:1
layerrule=noblur:1,noshadow:1,noanim:1,layer_name:quickshell

# tag rules
# tagrule=id:1,layout_name:tile
# tagrule=id:2,layout_name:manual_tile
# tagrule=id:3,layout_name:tile
# tagrule=id:4,layout_name:tile
# tagrule=id:5,layout_name:tile
# tagrule=id:6,layout_name:tile
# tagrule=id:7,layout_name:tile
# tagrule=id:8,layout_name:tile
# tagrule=id:9,layout_name:tile
